### ISSUE TITLE
[BUG] Sticky header functionality does not work

### ISSUE THREAD

**Issue by OlenaBulat** [Resultify/nimbly-lite#57]
**Describe the bug**
Sticky header functionality does not work. After the Sticky header toggle was switched ON, asset changes were published and saved, but still, nothing has happened to the site header. 

**To Reproduce**

1. Go to the Website pages in the HubSpot account. 
2. Click on Create button -> Website page and create a new page based on the Nimbly Light theme (Strat page template) OR use the existing page based on this theme. 
3. Click on the Edit button to open the page in the Editing mode
4. Click on the Contents tab -> Global header settings
5. In the pop-up form click on the 'Open in global content editor' button 
6. In the opened editor click again on the Contents tab -> Sticky header
7. Switch the toggle ON 
8. In the right top corner click on the 'Publish to _ assets" button to save changes 
9. Once changes were saved and the user was returned to the webpage (Editing mode) click on the 'Update' button in the right top corner
10. Open the saved page in the preview mode or in the new window tab

**Expected behavior**
After the Sticky header toggle was changed to ON site header menu should be sticky. 

**Additional context**
Tested on 2 accounts with Nimbly v.2 (one sandbox account with Nimbly Light v.2 and one demo account after updating Nimbly Light from v.1 to v.2)

**Comment by pxamike** [comment]
@OlenaBulat So was this tested without a child-theme?

With the merge of this commit ( https://github.com/Resultify/nimbly-lite-child/commit/5d0024f521180f010aab7adf5a9cc93a7c24f547) it should now work with child themes at least.
